# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87273-ECOMMERCE-DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_720eeff659bd40f29447ca3ac1328508 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7dac649ceedb428c99683c2228ad20dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_720eeff659bd40f29447ca3ac1328508 }}/checkpoint2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87273-ECOMMERCE-DEV'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_156f2def5f354b1496f043401b140076 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_720eeff659bd40f29447ca3ac1328508 }}/checkpoint2:${{ github.sha }}'